### ISSUE TITLE
Sets with 100% coverage are not included in --text-compact 

### ISSUE THREAD

**Issue by davelab6** [davelab6/pyfontaine#75]
The number of results for text and text-compact outputs should be the same, but they are not:

```
pyfontaine --collections fontconfig ofl/snippet/Snippet.ttf | grep Orthography | wc -l ;
 138
pyfontaine --text-compact --collections fontconfig ofl/snippet/Snippet.ttf | wc -l ;
  71
```

It seems all sets with 100% coverage are not included in the compact version, but they should be.

**Comment by felipesanches** [comment]
This was fixed by @vitalyvolkov on https://github.com/davelab6/pyfontaine/commit/8db4651a1b999ef2ba50b2c4bfb83f4941366340
